language: go

go:
- 1.x

os:
  - linux
  - windows
  - osx

branches:
  only:
    - master
    - develop
    - /^feature\/travis\/.+$/ # feature/travis/*
    - /^fix\/travis\/.+$/ # fix/travis/*

git:
  autocrlf: false

install:
  - go get -d -u github.com/golang/dep
  - go install github.com/golang/dep/cmd/dep
  - dep ensure
  - ./test install

script: ./test --scripted
